### ISSUE TITLE
Strukturarbeit

### ISSUE THREAD

**Issue by jannisgeorgi** [pinkehaende/website#1]
Hallo Fabi, 
kannst du dir mal bitte anschauen, wie ich für die Buttons auf der startseite eine aktion statt eine Seite hinterlegen kann ? 

zum Beispiel ein "mailto"

**Comment by anokfireball** [comment]
Was sind denn für dich _Aktionen_? `mailto:` im Speziellen ist auch nur ein Link, der als `href` eingebunden wird (siehe [`themes/pinkehaende-theme/layouts/partials/sub-footer.html`](https://github.com/pinkehaende/website-theme/blob/2db5c603007f0d90f19e546ec7604d17cd2fd73a/layouts/partials/sub-footer.html#L11)). Ein `mailto:`  ist btw schon an zwei Stellen im Code drin.

Wenn es dir  darum geht, zu einem Button einen Link zu hinterlegen, der nicht das relative URL Prefix der Website hat (also Refer auf `pinkefuesse.de`) oder eben eine andere _Aktion_ auslösen soll (also `mailto:jannis@pinkehaende.de`): Die Buttons sind auch mit `href` Parametern aus den Button-Templates realisiert (siehe zB [`themes/pinkehaende-theme/layouts/index.html`](https://github.com/pinkehaende/website-theme/blob/2db5c603007f0d90f19e546ec7604d17cd2fd73a/layouts/index.html#L32)). [relURL](https://gohugo.io/functions/relurl/) führt dazu, dass nicht-URIs (also `buttonLink: 'work'`) zu relativen URLs bezogen auf die aktuelle `baseURL` (also ` https://pinkehaende.de`) werden. In diesem Beispiel `/work`.
- Wenn es ein anderes Ziel sein soll, musst du in das `buttonLink` Feld die Komplette URL eintragen (also `https://pinkefuesse.de`), damit `relURL` daraus keine relative lokale Adresse interpretiert
- Wenn es eine andere _Aktion_ (also ein nicht-HTTP Ziel) sein soll, musst du vermutlich das `href="{{ .Params.buttonLink | relURL }}"` im Template anpassen. [Dokumentation](https://gohugo.io/templates/introduction/#example-4-if--else) zur Referenz. Beispiel, wie das _nur_ für `mailto:` aussehen könnte:
```html
{{ if (hasPrefix .Params.buttonLink "mailto:") }}
  <a class="button" href="{{ .Params.buttonLink }}">{{ .Params.button }}</a>
{{ else }}
  <a class="button" href="{{ .Params.buttonLink | relURL }}">{{ .Params.button }}</a>
{{ end }}
```

**Comment by anokfireball** [comment]
Gelöst mit #2.
